#!/usr/bin/env python3
"""
Download code datasets for sLLM training.

Streams vinsblack/The_Stack_Processed-v2 ONCE, collecting files
for Python, TypeScript, JavaScript, and Rust simultaneously.

Usage:
    python scripts/download_code.py [--output data/code/] \
        [--languages python,typescript,javascript,rust] \
        [--max-files-per-lang 5000] [--dry-run]
"""

import argparse
import os
import sys
from pathlib import Path


def ensure_deps():
    try:
        import datasets
    except ImportError:
        os.system(f"{sys.executable} -m pip install -q datasets")


# Language name -> file extension mapping
LANG_EXTENSIONS = {
    "python": ".py",
    "typescript": ".ts",
    "javascript": ".js",
    "rust": ".rs",
}


def download_all_languages(
    output_dir: Path,
    languages: list[str],
    max_files_per_lang: int,
    dry_run: bool = False,
) -> dict[str, int]:
    """Stream dataset ONCE, collecting all target languages simultaneously."""
    from datasets import load_dataset

    if dry_run:
        for lang in languages:
            print(f"  → {lang}: would download up to {max_files_per_lang} files")
        return {lang: 0 for lang in languages}

    # Track per-language counters
    counts = {}
    line_counts = {}
    for lang in languages:
        ext = LANG_EXTENSIONS.get(lang, f".{lang}")
        lang_dir = output_dir / lang
        lang_dir.mkdir(parents=True, exist_ok=True)
        existing = list(lang_dir.glob(f"*{ext}"))
        if len(existing) >= max_files_per_lang:
            print(f"  ✓ {lang}: already have {len(existing):,} files, skipping")
            counts[lang] = len(existing)
        else:
            counts[lang] = len(existing)  # Start from existing count
            line_counts[lang] = 0

    # Check if all languages are complete
    needed = [l for l in languages if l in line_counts]
    if not needed:
        return counts

    print(f"  ↓ Streaming The Stack Processed V2 for: {', '.join(needed)}")
    print(f"    Target: {max_files_per_lang} files per language")

    ds = load_dataset(
        "vinsblack/The_Stack_Processed-v2",
        split="train",
        streaming=True,
    )

    rows_seen = 0
    for row in ds:
        rows_seen += 1

        # Get language (lowercase for matching)
        row_lang = row.get("language", "").lower()
        if row_lang not in needed:
            continue

        content = row.get("content", "")
        if not content or len(content.strip()) < 50:
            continue

        # Unescape: The Stack Processed V2 stores \\n as literal escaped newlines
        content = content.replace("\\n", "\n").replace("\\t", "\t")

        # Basic quality filters
        lines = content.split("\n")
        if len(lines) > 5000 or len(lines) < 3:
            continue

        # Check for auto-generated markers
        first_lines = "\n".join(lines[:5]).lower()
        if any(marker in first_lines for marker in [
            "auto-generated", "do not edit", "generated by",
            "automatically generated", "machine generated",
        ]):
            continue

        # Write to file
        ext = LANG_EXTENSIONS.get(row_lang, f".{row_lang}")
        file_idx = counts[row_lang]
        out_path = output_dir / row_lang / f"{file_idx:06d}{ext}"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

        counts[row_lang] += 1
        line_counts[row_lang] = line_counts.get(row_lang, 0) + len(lines)

        if counts[row_lang] % 500 == 0:
            print(f"    {row_lang}: {counts[row_lang]:,} files ({line_counts[row_lang]:,} lines) [scanned {rows_seen:,} rows]")

        # Check if this language is done
        if counts[row_lang] >= max_files_per_lang:
            needed.remove(row_lang)
            print(f"  ✓ {row_lang}: {counts[row_lang]:,} files ({line_counts[row_lang]:,} lines)")
            if not needed:
                break

        # Safety: don't scan forever
        if rows_seen > 5_000_000:
            print(f"  ⚠ Scanned {rows_seen:,} rows, stopping early")
            break

    # Report what we got
    for lang in languages:
        if lang in line_counts and lang not in [l for l in languages if counts.get(l, 0) >= max_files_per_lang]:
            print(f"  ✓ {lang}: {counts[lang]:,} files ({line_counts.get(lang, 0):,} lines) [partial]")

    return counts


def create_combined_corpus(output_dir: Path, languages: list[str]):
    """Create a single combined .txt file for each language."""
    for lang in languages:
        lang_dir = output_dir / lang
        ext = LANG_EXTENSIONS.get(lang, f".{lang}")
        combined = output_dir / f"{lang}_combined.txt"

        if combined.exists():
            continue

        files = sorted(lang_dir.glob(f"*{ext}"))
        if not files:
            continue

        print(f"  ⚙ Combining {len(files)} {lang} files → {combined.name}...")
        total_lines = 0
        with open(combined, "w", encoding="utf-8") as out:
            for f in files:
                content = f.read_text(encoding="utf-8", errors="replace")
                out.write(f"<|file|>\n{content}\n<|endfile|>\n")
                total_lines += content.count("\n") + 1

        print(f"  ✓ {lang}: {total_lines:,} lines → {combined.name}")


def main():
    parser = argparse.ArgumentParser(description="Download code training data")
    parser.add_argument("--output", default="data/code")
    parser.add_argument("--languages", default="python,typescript,javascript,rust")
    parser.add_argument("--max-files-per-lang", type=int, default=5000)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    output_dir = Path(args.output)
    if not output_dir.is_absolute():
        root = Path(__file__).parent.parent
        output_dir = root / output_dir

    output_dir.mkdir(parents=True, exist_ok=True)
    languages = [l.strip() for l in args.languages.split(",")]

    ensure_deps()

    print(f"{'DRY RUN — ' if args.dry_run else ''}Downloading code datasets → {output_dir}")
    print(f"Languages: {', '.join(languages)}")
    print(f"Max files per language: {args.max_files_per_lang:,}")
    print("=" * 60)

    results = download_all_languages(output_dir, languages, args.max_files_per_lang, args.dry_run)

    if not args.dry_run:
        print("\nCombining files into training corpora...")
        create_combined_corpus(output_dir, languages)

    print("=" * 60)
    for lang, count in results.items():
        print(f"  {lang}: {count:,} files")
    print(f"Total: {sum(results.values()):,} files")


if __name__ == "__main__":
    main()
