#!/usr/bin/env python3
"""
Download code datasets for sLLM training.

Sources:
  - vinsblack/The_Stack_Processed-v2 (pre-cleaned, no auth needed)
  - Falls back to bigcode/starcoderdata if available

Filters to: Python, TypeScript, JavaScript, Rust only.

Usage:
    python scripts/download_code.py [--output data/code/] \
        [--languages python,typescript,javascript,rust] \
        [--max-files-per-lang 10000] [--dry-run]
"""

import argparse
import os
import sys
from pathlib import Path


def ensure_deps():
    try:
        import datasets
    except ImportError:
        os.system(f"{sys.executable} -m pip install -q datasets")


# Language name -> file extension mapping
LANG_EXTENSIONS = {
    "python": ".py",
    "typescript": ".ts",
    "javascript": ".js",
    "rust": ".rs",
}


def download_stack_processed(
    output_dir: Path,
    languages: list[str],
    max_files_per_lang: int,
    dry_run: bool = False,
) -> dict[str, int]:
    """Download pre-cleaned code from The Stack Processed V2."""
    from datasets import load_dataset

    results = {}

    for lang in languages:
        ext = LANG_EXTENSIONS.get(lang, f".{lang}")
        lang_dir = output_dir / lang
        lang_dir.mkdir(parents=True, exist_ok=True)

        # Check if already done
        existing = list(lang_dir.glob(f"*{ext}"))
        if len(existing) >= max_files_per_lang:
            print(f"  ✓ {lang}: already have {len(existing):,} files, skipping")
            results[lang] = len(existing)
            continue

        if dry_run:
            print(f"  → {lang}: would download up to {max_files_per_lang} files")
            results[lang] = 0
            continue

        print(f"  ↓ {lang}: downloading from The Stack Processed V2...")

        try:
            # Try the processed version first (no auth)
            ds = load_dataset(
                "vinsblack/The_Stack_Processed-v2",
                split="train",
                streaming=True,
                trust_remote_code=True,
            )

            file_count = 0
            total_lines = 0

            for row in ds:
                # Filter by language
                row_lang = row.get("language", row.get("lang", "")).lower()
                if row_lang != lang:
                    continue

                content = row.get("content", row.get("code", row.get("text", "")))
                if not content or len(content.strip()) < 50:
                    continue

                # Basic quality filters
                lines = content.split("\n")
                if len(lines) > 5000:  # Skip very large files
                    continue
                if len(lines) < 3:  # Skip trivially small files
                    continue

                # Check for auto-generated markers
                first_lines = "\n".join(lines[:5]).lower()
                if any(marker in first_lines for marker in [
                    "auto-generated", "do not edit", "generated by",
                    "automatically generated", "machine generated",
                ]):
                    continue

                # Write to file
                out_path = lang_dir / f"{file_count:06d}{ext}"
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(content)

                file_count += 1
                total_lines += len(lines)

                if file_count % 1000 == 0:
                    print(f"    {lang}: {file_count:,} files ({total_lines:,} lines)...")

                if file_count >= max_files_per_lang:
                    break

            print(f"  ✓ {lang}: {file_count:,} files ({total_lines:,} lines)")
            results[lang] = file_count

        except Exception as e:
            print(f"  ✗ {lang}: failed — {e}")
            results[lang] = 0

    return results


def create_combined_corpus(output_dir: Path, languages: list[str]):
    """Create a single combined .txt file for each language (for training)."""
    for lang in languages:
        lang_dir = output_dir / lang
        ext = LANG_EXTENSIONS.get(lang, f".{lang}")
        combined = output_dir / f"{lang}_combined.txt"

        if combined.exists():
            continue

        files = sorted(lang_dir.glob(f"*{ext}"))
        if not files:
            continue

        print(f"  ⚙ Combining {len(files)} {lang} files → {combined.name}...")
        total_lines = 0
        with open(combined, "w", encoding="utf-8") as out:
            for f in files:
                content = f.read_text(encoding="utf-8", errors="replace")
                # Add file separator for the tokenizer
                out.write(f"<|file|>\n{content}\n<|endfile|>\n")
                total_lines += content.count("\n") + 1

        print(f"  ✓ {lang}: {total_lines:,} lines → {combined.name}")


def main():
    parser = argparse.ArgumentParser(description="Download code training data")
    parser.add_argument("--output", default="data/code")
    parser.add_argument("--languages", default="python,typescript,javascript,rust")
    parser.add_argument("--max-files-per-lang", type=int, default=10000)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    output_dir = Path(args.output)
    if not output_dir.is_absolute():
        root = Path(__file__).parent.parent
        output_dir = root / output_dir

    output_dir.mkdir(parents=True, exist_ok=True)
    languages = [l.strip() for l in args.languages.split(",")]

    ensure_deps()

    print(f"{'DRY RUN — ' if args.dry_run else ''}Downloading code datasets → {output_dir}")
    print(f"Languages: {', '.join(languages)}")
    print(f"Max files per language: {args.max_files_per_lang:,}")
    print("=" * 60)

    results = download_stack_processed(output_dir, languages, args.max_files_per_lang, args.dry_run)

    if not args.dry_run:
        print("\nCombining files into training corpora...")
        create_combined_corpus(output_dir, languages)

    print("=" * 60)
    for lang, count in results.items():
        print(f"  {lang}: {count:,} files")
    print(f"Total: {sum(results.values()):,} files")


if __name__ == "__main__":
    main()
